// =================================================================
// Stock-Keeper UI Prototype V4 - Control Panel
// Dynamic control panel generation from screens.json
// =================================================================

let config = null;
let currentPhase = 'P1';

/**
 * Initialize control panel from config
 * @param {Object} screenConfig - screens.json configuration
 */
export async function initControlPanel(screenConfig) {
    config = screenConfig;
    const panel = document.getElementById('control-panel');
    if (!panel) return;

    // Restore Position


    // Render Unified Control Panel
    // 1. Drag Handle
    // 2. Phase Buttons (Now inside)
    // 3. App Controls
    // 4. Theme Toggle
    // 5. Columns
    panel.innerHTML = `
        <!-- Drag Handle -->
        <div class="cp-drag-handle" title="Drag to move"></div>

        <!-- Phase Control (Integrated) -->
        <div id="control-panel-phase" class="control-panel-phase">
            ${config.phases.map(p => `
                <button class="phase-btn ${p === currentPhase ? 'active' : ''}" 
                        data-phase="${p}" 
                        onclick="setPhase('${p}')">${p}</button>
            `).join('')}
        </div>

        <!-- App Control -->
        <div class="control-app-row">
            <button class="app-start-btn" id="app-start-btn" onclick="startApp()" data-title="앱 시작">🚀</button>
            <button class="app-reset-btn" onclick="resetApp()" data-title="초기화">🔄</button>
        </div>
        
        <!-- Theme Toggle -->
        <div class="control-theme-row">
            <label class="mode-toggle">
                <input type="checkbox" id="mode-toggle-input" checked>
                <span class="mode-toggle-slider"></span>
            </label>
        </div>
        
        <div class="control-columns" id="control-columns">
            <!-- Columns will be dynamically generated by phase -->
        </div>
    `;

    renderNavButtons();

    // Init Draggable
    import('./utils/draggable.js').then(({ makeDraggable }) => {
        const handle = panel.querySelector('.cp-drag-handle');
        makeDraggable(panel, handle, 'cp-position');
    });

    // 🆕 초기화 시점 동기화
    document.body.setAttribute('data-current-phase', currentPhase);
}
function renderNavButtons() {
    const columnsContainer = document.getElementById('control-columns');
    if (!columnsContainer) return;

    // Get visible screens filtered by current phase
    const visibleScreens = config.screens
        .filter(s => config.phases.indexOf(s.phase) <= config.phases.indexOf(currentPhase))
        .sort((a, b) => a.navButton.order - b.navButton.order);

    // Group screens by phase
    const screensByPhase = {};
    visibleScreens.forEach(screen => {
        if (!screensByPhase[screen.phase]) {
            screensByPhase[screen.phase] = [];
        }
        screensByPhase[screen.phase].push(screen);
    });

    // Build columns HTML
    let columnsHTML = '';

    // Iterate through phases in order
    config.phases.forEach(phase => {
        if (screensByPhase[phase] && screensByPhase[phase].length > 0) {
            columnsHTML += `
                <div class="nav-column" data-phase="${phase}">
                    ${screensByPhase[phase].map(screen => `
                        <button class="nav-btn" 
                                data-screen="${screen.id}" 
                                data-title="${screen.name}">${screen.navButton.icon}</button>
                    `).join('')}
                </div>
            `;
        }
    });

    // Add state column at the end
    columnsHTML += `<div class="state-column" id="state-column"></div>`;

    columnsContainer.innerHTML = columnsHTML;

    // Re-render state buttons after nav columns are created
    renderStateButtons();
}

/**
 * Render state buttons for all screens
 */
function renderStateButtons() {
    const stateColumn = document.getElementById('state-column');
    if (!stateColumn) return;

    const allStateButtons = [];

    config.screens.forEach(screen => {
        screen.stateButtons?.forEach(btn => {
            allStateButtons.push(`
                <button class="state-btn" 
                        data-for-screens="${screen.id}"
                        data-state="${btn.id}"
                        data-title="${btn.title}"
                        onclick="toggleState('${screen.id}', '${btn.id}', this)">${btn.icon}</button>
            `);
        });
    });

    stateColumn.innerHTML = allStateButtons.join('');
}

/**
 * Set current phase filter
 * @param {string} phase - Phase to set (P1, P2, P3)
 */
window.setPhase = function (phase) {
    currentPhase = phase;

    // Update phase button states
    document.querySelectorAll('.phase-btn').forEach(btn => {
        btn.classList.toggle('active', btn.dataset.phase === phase);
    });

    // Re-render nav buttons
    renderNavButtons();

    // Re-init navigation listeners
    document.querySelectorAll('.nav-btn').forEach(btn => {
        btn.addEventListener('click', () => {
            import('./navigation.js').then(nav => nav.navigateTo(btn.dataset.screen));
        });
    });

    // 🆕 신규: 화면 내부 요소 토글용 data 속성
    document.body.setAttribute('data-current-phase', phase);

    // 🆕 탭바 표시/숨김 처리
    import('./tab-bar.js').then(tabBar => {
        import('./navigation.js').then(nav => {
            const currentScreenId = nav.getCurrentScreen();
            tabBar.handlePhaseChange(phase, currentScreenId, nav.navigateTo);
        });
    });
};

/**
 * Toggle state for a screen
 */
window.toggleState = function (screenId, stateId, btnElement) {
    // 1. Toggle Active State
    const wasActive = btnElement.classList.contains('active');

    // De-activate all buttons for this screen first (Mutually Exclusive)
    const siblings = document.querySelectorAll(`.state-btn[data-for-screens="${screenId}"]`);
    siblings.forEach(btn => btn.classList.remove('active'));

    // Activate clicked button if it wasn't already active
    if (!wasActive) {
        btnElement.classList.add('active');
    }

    const newState = !wasActive ? stateId : 'default';

    // 2. Call updateScreenState directly (from navigation.js)
    console.log(`[ControlPanel] State Changed: ${screenId} -> ${newState}`);

    // Use the global function exposed by navigation.js
    if (window.updateScreenState) {
        window.updateScreenState(screenId, newState);
    }

    // Also dispatch event for any other listeners
    const event = new CustomEvent('app-state-change', {
        detail: {
            screenId: screenId,
            state: newState
        }
    });
    window.dispatchEvent(event);
};

// ===================================
// Draggable Logic
// ===================================

// Draggable logic moved to core/utils/draggable.js

export { currentPhase };
